### ISSUE TITLE
Feature request: add an option to change buttons size in editor

### ISSUE THREAD

**Issue by aPaci95** [AnKingMed/Browser-Resizer#9]
Would it be possible to add an option to change buttons size and/or padding in editor ? With 2.1.45 they became enormous...

**Comment by AnKingMed** [comment]
I'm not 100% sure if it is or not. My guess is probably in this area of the code: https://github.com/AnKingMed/Browser-Resizer/blob/e875e053283b82af44086486e368cdab255cfd2e/sources/css/editable.css#L1

If you know html you can try it out (should be relatively simple).  Otherwise I'll try looking into it in ~2 weeks when I have some free time

**Comment by aPaci95** [comment]
Thank you very much! If you have time please consider adding it to browser resizer, as it would be awesome to have a single addon that does it instead of having to manually edit the code everytime anki updates...
Thanks again and have a nice day!

**Comment by AnKingMed** [comment]
Do you have the code that you're editing to make it work? That would make it easier for me

**Comment by aPaci95** [comment]
I'm sorry but I couldn't get it to work...

**Comment by abdnh** [comment]
It's now possible to customize the buttons size using the `editor button font size` and `editor button size` options.
![image](https://github.com/AnKing-VIP/Browser-Resizer/assets/41397710/7913a29a-7a33-4dbd-8a86-99fcde5a34a4)
